on:
  workflow_dispatch:

jobs:
  release-on-push:
    runs-on: ubuntu-latest
    environment: prod
    #env:
    #  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Get environment configuration
        run: |
          echo "Trick to echo GitHub Actions Secret:  "
          echo "${{secrets.CONFIG}}" | sed 's/./& /g' > inputs.yml

      - name: Find out where we are
        run: |
          ls -lart
          pwd 

      - name: Run a plan
        run: |
          cd environment/component1
          terragrunt plan


      
