on:
  workflow_dispatch:

jobs:
  release-on-push:
    runs-on: ubuntu-latest
    environment: prod
    #env:
    #  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - shell: bash
        run: |
          echo "The GitHub Action Secret will be masked:  "
          echo ${{ secrets.CONFIG }}
          echo "Trick to echo GitHub Actions Secret:  "
          echo ${{secrets.CONFIG}} | sed 's/./& /g' 